# top level stuff you probably don't need to touch
# highlighter: pygments
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: :title.html
# paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://end2endsystems.com.br/
baseurl: /
title: Matheus Costa Vieira
author: Matheus Costa Vieira
description: Personal blog and resume
avatar: profile.jpg
email: matheus@end2endsystems.com.br
github: matheus-vieira
twitter: macostavieira
linkedin: macostavieira
facebook: macovieira
googleplus: MatheusCostaVieira
disqus: username
google_analytics: UA-69391421-1