# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /blog/article/:title.html


gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.end2endsystems.com.br/
title: Matheus Costa Vieira
author: Matheus Costa Vieira
description: Personal blog and resume
avatar: profile.png
email: matheus@end2endsystems.com.br


github: matheus-vieira
twitter: macostavieira
linkedin: macostavieira
facebook: macovieira
googleplus: MatheusCostaVieira
disqus: matheuscostavieira

google_analytics: UA-27171689-1